### ISSUE TITLE
write a simple integration test

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/ca.berlin.freifunk.net#16]
We should write a simple integration test that is part of the travis run. The test should create a request for a certificate and we should check the database for the proper content.

**Comment by carpodaster** [comment]
I'm not familiar with python, but I'm pretty well-versed with Ruby's web testing frameworks. I'd be happy to look into it, though. Any pointers about what Python-people use for testing?

**Comment by andrenarchy** [comment]
I can recommend [nosetests](https://nose.readthedocs.org/en/latest/). Here's a project where I use it with travis: https://github.com/andrenarchy/krypy.

**Comment by k-nut** [comment]
I just looked into this and used the [official guide to testing flask apps](http://flask.pocoo.org/docs/0.10/testing/) as a template.

I think this does not work for us though. We want to create a new sqlite database for every test run like they are doing it in the example. But since we are only setting the `db` variable once (https://github.com/freifunk-berlin/ca.berlin.freifunk.net/blob/master/app.py#L8) we are not able to change the apps' `SQLALCHEMY_DATABASE_URI` like in the example (we also must manually call `db.create_all()` on it first).

Do I see this correctly or am I missing something?

**Comment by booo** [comment]
It's no problem to change code a little bit to allow testing.

I think it's enough to delete the content from the table. We don't have to recreate the database with each run.

**Comment by k-nut** [comment]
I created a new branch for this. Feedback much appreciated!  https://github.com/freifunk-berlin/ca.berlin.freifunk.net/tree/tests

**Comment by booo** [comment]
Thanks for working on this! Excellent job.

**Comment by k-nut** [comment]
I am not sure by the way if the setup of the database actually works. Maybe the config is just taken once at the beginning and we overwrite the database that is set in the config file. I guess it would be smart to check this. Or just not run the tests on production ;)

**Comment by booo** [comment]
I don't quite get what you mean. If you think there is a problem please create a ticket for the problem so we can work on it.

But I think the setup of the tests is fine.
