### ISSUE TITLE
import script

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/ca.berlin.freifunk.net#5]
For our initial import we need a script.

/etc/openvpn/ contains one directory easy-rsa/keys that contains crts, keys and csrs. There is also a clients directory with a tgz file that contains everything you receive via mail from us. The tars and the certs, etc. have a prefix 'freifunk_' followed by the key id.

**Comment by booo** [comment]
@k-nut do you need more detailed information about the problem or is this fine?

**Comment by k-nut** [comment]
I think that should be enough. I will not get around to implementing it until next weekend though since I am on vacation now.  
I would just create a new branch then and implement it as far as I understand it and then we can always make changes if there is something that I did not get right.

Actually if you want you could send me the output of `tree` in the `/etc/openvpn/` directory via mail so that I can be sure to get it right :)

**Comment by booo** [comment]
I created a first version of the import file. I'm not happy with the openssl dependency but it's not a problem we should invest much power in. I'm not sure how we should handle the datetime field and what we should do about the timezone. Your feedback is much appreciated.

**Comment by k-nut** [comment]
I think this is fine. Since it will only be run once it does not need to be super pretty. The timezone should always be the same so we can just drop it, right? The only thing of interest to us is the date and not the time anyway if I remember correctly and that is not so much influenced by the timezone.

**Comment by k-nut** [comment]
Do we still need to do anything here?

**Comment by booo** [comment]
I think it's done.
