### ISSUE TITLE
add simple captcha

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/ca.berlin.freifunk.net#7]
We should add a simple captcha to the form. Maybe the same we use at config.berlin.freifunk.net.

**Comment by k-nut** [comment]
Is this really necessary? Captchas are incredibly bad for user experience and make websites much less accessible on many levels. 

I think that asking a question as on config.berlin.freifunk.net would be okay but maybe using a hidden honeypot form field as described in [this article](https://moz.com/blog/having-a-captcha-is-killing-your-conversion-rate) might be an even better alternative. 

No matter what we do I think it would be very interesting to see, how many failed attempts the captcha gets so that we can check if it is due to actual bots (good) or failed user attempts (bad).

I do not have experience with this though so if you say that it works well for you on the config website I am fine with that :)

**Comment by booo** [comment]
I think it's enough if we use the question from config.berlin here too.

**Comment by k-nut** [comment]
okay, will add that

**Comment by booo** [comment]
I think this is done.
